### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by peger089**
Accomodation and location information added.

### CODE REVIEW

**Comment by peger089** [comment]
Hotel information added.

**Comment by cdeil** [comment]
:sunrise:  Welcome to Github. :sunrise: 

https://github.com/peger089

**Comment by cdeil** [comment]
If you like, you can commit directly to the `gh-pages` branch (for this I don't get an email notification).

Making a pull request is mainly useful if something needs discussion or review (for pull requests I do get an email notification).

**Comment by cdeil** [comment]
I've included this info in the document ...

**Pull request closed without merging**
