### PR TITLE
updated CTA talk  readme

### PR DESCRIPTION
**Pull request by kosack**

### CODE REVIEW

**Comment by cdeil** [comment]
:+1: 

Can I merge? Or did you want to update https://github.com/gammapy/2015-MPIK-Workshop/blob/gh-pages/tutorials/ctapipe/README.md in this PR as well?

**Comment by kosack** [comment]
I haven't had time to update the tutorials page (that will take much more time, since I need to figure out what to do, and put in all the details). You can merge the talk for now though!

**Comment by cdeil** [comment]
OK, merging this now.

Concerning the tutorial: there should be some info when the workshop announcement goes out and potential participants look at this to decide if they want to come to this workshop.

So please put something for now. It can be very short (just a few bullet points) and vague (e.g. "high performance computing" or "CTA shower example") and you're allowed to change it any time.

I know developing a detailed plan for the tutorial and examples will take time, this can happen up to shortly before the workshop ... for now the purpose is to give a rough idea for potential workshop participants.

**Comment by cdeil** [comment]
Thanks

**Pull request merged**
